name: getogp

on:
  push:
    tags:
      - 'getogp/*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/nasa9084/getogp
          tags: |
            type=match,pattern=getogp/(.*),group=1

      - uses: docker/build-push-action@v5
        with:
          context: ./getogp
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
